channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.7.13
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - addict==2.4.0
    - astunparse==1.6.3
    - attrs==22.2.0
    - backcall==0.2.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - configargparse==1.5.3
    - cycler==0.11.0
    - dash==2.9.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - entrypoints==0.4
    - fastjsonschema==2.16.3
    - flask==2.2.3
    - flatbuffers==22.9.24
    - fonttools==4.38.0
    - gast==0.3.3
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - h5py==2.10.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.12.0
    - ipykernel==6.16.2
    - ipython==7.34.0
    - ipywidgets==8.0.4
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==7.4.9
    - jupyter-core==4.12.0
    - jupyterlab-widgets==3.0.5
    - keras==2.11.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - numpy==1.21.6
    - nvidia-cublas==11.5.1.101
    - nvidia-cublas-cu11==2022.4.8
    - nvidia-cublas-cu117==11.10.1.25
    - nvidia-cuda-nvrtc==11.1.105
    - nvidia-cuda-runtime==11.3.58
    - nvidia-cuda-runtime-cu11==2022.4.25
    - nvidia-cuda-runtime-cu117==11.7.60
    - nvidia-cudnn==8.2.0.51
    - nvidia-cudnn-cu11==2022.5.19
    - nvidia-cudnn-cu116==8.4.0.27
    - nvidia-pyindex==1.0.9
    - nvidia-tensorrt==7.2.3.4
    - oauthlib==3.2.2
    - open3d==0.17.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.5
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.13.1
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-version==0.0.2
    - pytz==2022.5
    - pyyaml==6.0
    - pyzmq==25.0.2
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.4.1
    - six==1.16.0
    - tenacity==8.2.2
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.30.0
    - tensorrt==8.5.3.1
    - termcolor==2.0.1
    - threadpoolctl==3.1.0
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - wrapt==1.14.1
    - zipp==3.10.0
